version: "3.7"

services:
  # The Master node handles HDFS NameNode, YARN ResourceManager, and runs your scripts
  cluster-master:
    image: firasj/spark-docker-cluster
    container_name: cluster-master
    hostname: cluster-master
    ports:
      - "8088:8088"   # YARN UI
      - "4040:4040"   # Spark UI
      - "9870:9870"   # HDFS UI
      - "9000:9000"   # HDFS RPC
    volumes:
      - "./app:/app"  # Maps your local 'app' folder to '/app' in the container
    networks:
      - spark-cluster
    depends_on:
      - cluster-slave-1
      - cassandra-server
    tty: true
    working_dir: /app
    # This automatically triggers your assignment when the TA runs 'docker compose up'
    entrypoint: 
      - bash
      - /app/app.sh

  # The Slave node handles HDFS DataNode and YARN NodeManager
  cluster-slave-1:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-1
    hostname: cluster-slave-1
    
    networks:
      - spark-cluster
    tty: true

  # NoSQL Database for storing the Inverted Index and Stats
  cassandra-server:
    image: cassandra:latest
    container_name: cassandra-server
    hostname: cassandra-server
    ports:
      - "9042:9042"
    networks:
      - spark-cluster
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    deploy:
      resources:
        limits:
          memory: 1G
    # -------------------------
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 20s # Increased interval to give it more time
      timeout: 10s
      retries: 10

networks:
  spark-cluster:
    driver: bridge